//
// Event.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Event: JSONEncodable {
    public enum EventType: String { 
        case meetup = "meetup"
        case hacknight = "hacknight"
    }
    public var address: String?
    public var addressDisplay: String?
    public var contact: String?
    public var contactName: String?
    public var endsAt: String?
    public var eventType: EventType?
    public var lat: Double?
    public var lng: Double?
    public var location: String?
    public var locationLink: String?
    public var startsAt: String?
    public var subtitle: String?
    public var tickets: String?
    public var title: String?
    public var url: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["address"] = self.address
        nillableDictionary["address_display"] = self.addressDisplay
        nillableDictionary["contact"] = self.contact
        nillableDictionary["contact_name"] = self.contactName
        nillableDictionary["ends_at"] = self.endsAt
        nillableDictionary["event_type"] = self.eventType?.rawValue
        nillableDictionary["lat"] = self.lat
        nillableDictionary["lng"] = self.lng
        nillableDictionary["location"] = self.location
        nillableDictionary["location_link"] = self.locationLink
        nillableDictionary["starts_at"] = self.startsAt
        nillableDictionary["subtitle"] = self.subtitle
        nillableDictionary["tickets"] = self.tickets
        nillableDictionary["title"] = self.title
        nillableDictionary["url"] = self.url
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
