//
// EventsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class EventsAPI: APIBase {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getEvents(completion: @escaping ((_ data: EventsResponse?,_ error: Error?) -> Void)) {
        getEventsWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /events
     - Returns all published, upcoming events.
     - examples: [{contentType=application/json, example={
  "events" : [ {
    "address" : "Level 3, 469 La Trobe Street, Melbourne VIC 3000",
    "address_display" : "Level 3, 469 La Trobe Street, Melbourne",
    "contact" : "mailto:jesse@jcmultimedia.com.au",
    "contact_name" : "Jesse Collis",
    "ends_at" : "2017-04-13T11:30:00+0000",
    "event_type" : "meetup",
    "lat" : -37.8126541,
    "lng" : 144.9551303,
    "location" : "Outware",
    "location_link" : "http://www.outware.com.au/contact",
    "starts_at" : "2017-04-13T08:30:00+0000",
    "subtitle" : "Melbourne CocoaHeads Meetup",
    "tickets" : "https://www.meetup.com/Melbourne-CocoaHeads/",
    "title" : "Melbourne CocoaHeads #104",
    "url" : "https://www.melbournecocoaheads.com/events/meetup-2017-04-13"
  } ]
}}]

     - returns: RequestBuilder<EventsResponse> 
     */
    open class func getEventsWithRequestBuilder() -> RequestBuilder<EventsResponse> {
        let path = "/events"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<EventsResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
