//
// Address.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Address: Codable {
    /** Display string for the location */
    public var display: String
    public var location: Coordinate

    public init(display: String, location: Coordinate) {
        self.display = display
        self.location = location
    }
}
