//
// EventLinks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EventLinks: Codable {
    public var _self: String
    /** Optional web link to RSVP or purchase tickets */
    public var tickets: String?
    /** Web link for this event on melbournecocoaheds.com */
    public var web: String
    /** Web link to the venue or location&#39;s website */
    public var location: String

    public init(_self: String, tickets: String?, web: String, location: String) {
        self._self = _self
        self.tickets = tickets
        self.web = web
        self.location = location
    }

    public enum CodingKeys: String, CodingKey {
        case _self = "self"
        case tickets
        case web
        case location
    }
}
