//
// InlineResponse200.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse200: Codable {
    public var data: [Event]
    public var links: Links

    public init(data: [Event], links: Links) {
        self.data = data
        self.links = links
    }
}
